### ISSUE TITLE
fix rego files related to ACK

### ISSUE THREAD

**Issue by shahinshirvani** [prancer-io/prancer-compliance-test#278]
sample templates for ACK are like these:
```
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: $TABLE_NAME
spec:
  tableName: $TABLE_NAME
  attributeDefinitions:
    - attributeName: ForumName
      attributeType: S
    - attributeName: Subject
      attributeType: S
    - attributeName: LastPostDateTime
      attributeType: S
```
so we should use this kind of rule
```
default dynamodb_encrypt = null

aws_issue["dynamodb_encrypt"] {
    lower(input.kind) == "table"
    lower(input.spec.sseSpecification.sseType) == "aes256"
}

dynamodb_encrypt {
    lower(input.kind) == "table"
    not aws_issue["dynamodb_encrypt"]
}

dynamodb_encrypt = false {
    aws_issue["dynamodb_encrypt"]
}

dynamodb_encrypt_err = "AWS DynamoDB encrypted using AWS owned CMK instead of AWS managed CMK" {
    aws_issue["dynamodb_encrypt"]
}
```
